"""add portal description

Revision ID: 7f52307e0935
Revises: ebe458b98ccc
Create Date: 2026-07-19 13:09:55.009158
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f52307e0935'
down_revision: Union[str, None] = 'ebe458b98ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
