"""initial schema

Revision ID: ebe458b98ccc
Revises: 
Create Date: 2026-07-19 13:09:06.500744
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ebe458b98ccc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_roles',
    sa.Column('portal_slug', sa.String(), nullable=False),
    sa.Column('module_type', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('portal_slug', 'module_type', 'role')
    )
    op.create_table('portal_roles',
    sa.Column('portal_slug', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('portal_slug', 'role')
    )
    op.create_table('portals',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('catalog', sa.String(), nullable=False),
    sa.Column('portal_config', sa.JSON(), nullable=False),
    sa.Column('layer_config', sa.JSON(), nullable=False),
    sa.Column('active_snapshot_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portals_catalog'), ['catalog'], unique=False)

    op.create_table('rest_services',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('catalog', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('rest_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rest_services_catalog'), ['catalog'], unique=False)

    op.create_table('service_roles',
    sa.Column('service_key', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('service_key', 'role')
    )
    op.create_table('services',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('catalog', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('upstream_auth_env', sa.String(), nullable=True),
    sa.Column('allow_transactions', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_catalog'), ['catalog'], unique=False)

    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_slug', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshots_portal_slug'), ['portal_slug'], unique=False)

    op.create_table('styles',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('catalog', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('styles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_styles_catalog'), ['catalog'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('styles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_styles_catalog'))

    op.drop_table('styles')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_portal_slug'))

    op.drop_table('snapshots')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_catalog'))

    op.drop_table('services')
    op.drop_table('service_roles')
    with op.batch_alter_table('rest_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rest_services_catalog'))

    op.drop_table('rest_services')
    with op.batch_alter_table('portals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portals_catalog'))

    op.drop_table('portals')
    op.drop_table('portal_roles')
    op.drop_table('module_roles')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
